### ISSUE TITLE
publish version 2.5.1

### ISSUE THREAD

**Issue by jtrs** [cubbles/cubx.core.rte#23]
update and publish the repositories:
* [ ] rte
* [ ] cubx-grunt-webpackage-scaffold
* [ ] cubx-wct-scaffolder
* [ ] update cubbles-test
