### ISSUE TITLE
eliminate vulnerability issues 

### ISSUE THREAD

**Issue by jtrs** [cubbles/cubx.core.rte#26]
Github found potential security vulnerabilities in  dependencies.

Some of the dependencies defined in these manifest files have known security vulnerabilities and should be updated:

tj / node-growl growl
wycats / handlebars.js handlebars
TooTallNate / node-https-proxy-agent https-proxy-agent
lodash / lodash
moment / moment
get / parsejson
visionmedia / superagent
mishoo / UglifyJS2 uglify-js  
...

Update packages to 
* [x] lodash#4.17.10
* [x] grunt#1.0.3
* [x] mocha#5.2.0
* [x] karma#3.0.0
* [x] sinon#6.1.5
* [x] sinon-chai#3.2.0
* [x] karma-chrome-launcher#2.2.0
* [x] karma-firefox-launcher#1.1.0
* [x] karma-htmlfile-reporter#0.3.6",
* [x] karma-mocha#1.3.0
* [x] karma-mocha-reporter#2.2.5
* [x] grunt-karma#2.0.0 -> It had to be updated to 3.0.0
* ~~[ ] cubx-karma-requirejs#?~~ -> does not represent a vulnerability
* ~~[ ] cubx-requirejs#?~~ -> does not represent a vulnerability

#### Merging and inclusion
* [x] Merge into develop_2x branch
* [x] Include/adapt in develop branch

**Comment by edwingamboa** [comment]
#### About karma tests
There was not a problem with requirejs. The problem was related to the fact that Karma started the tests before requirejs was ready. This issue should have been solved by [this line](https://github.com/cubbles/cubx-karma-requirejs/blob/51dac70da9e8e751ed1dc75b63b0fd6560308ec7/lib/adapter.js#L55) of our cubx-karma-requirejs adaptar like in the original version of the karma-requirejs adapter. However, it seems that the new Karma version behaves differently. I found out that Karma was calling karma.start method, so I redefined the method as [an empty function](https://github.com/cubbles/cubx.core.rte/blob/b930fb8f9bff0380378a33936257ee7fc5f0a75a/webpackages/cubx.core.rte/crc/test/testMain.js#L13). Since we use Mocha to run our tests, karma.start equivalent to run mocha.run, which [is called later](https://github.com/cubbles/cubx.core.rte/blob/b930fb8f9bff0380378a33936257ee7fc5f0a75a/webpackages/cubx.core.rte/crc/test/testMain.js#L38) when requirejs is ready.
The solution was applyied in `crc` and `crc-loader` tesMain.js files.

#### About vulnerabilities
I updated oder dependencies to eliminate vulnerabilities:

grunt-karma, grunt-contrib-csslint, grunt-githooks, grunt-jsdoc, load-grunt-configs, load-grunt-tasks, cubx-grunt-wct-scaffolder

However, there are still other vulnerabilities that should be resolved in the orginal modules, some of them are our CDT related modules (e.g. cubx-grunt-http-server, cubx-grunt-prepare-webpackage-release, cubx-grunt-webpackage-upload)

The whole vulnerability issues report is available [online](https://gist.github.com/edwingamboa/cdba5a2ecf084be2ef9689208fe7c028).

#### Question
We are updating the pacakge.json file from devetools folder. My question is, shouldn't the vulnerailities be fixed in the CDT repo? and, if we have additional deps in RTE, shouldn't we find a way to separate both things, at least in orginal repo of CDT (e.g. with a branch)?

**Comment by jtrs** [comment]
Please merge in develop_2x branch and include in develop branch.
